### PR TITLE
Fix #49 - Unable to import AbstractUserCreationForm or AbstractUserChangeForm independently of package

### LINKED ISSUE #49: Unable to import AbstractUserCreationForm or AbstractUserChangeForm independently of package
## Specifications

- Platform/System: macOS 10.12.6
- Python Version: 3.6.2
- Django Version: 1.11.6
- Improved User Version: 1.0a1

## Expected Behavior
In a Django project, if I can import the abstract models, I should also be able to import the abstract forms. I can also see instances where extending the `UserFactory` class could be useful. To provide the greatest flexibility, this project should use Django's `get_user_model()` function in all locations where it needs to reference the User model.

## Actual Behavior
Just as Issue #36 described an inability to import the mix-in model classes without needing to add `improved_user` to `INSTALLED_APPS`, the same error occurs when attempting to import `AbstractUserCreationForm` or `AbstractUserChangeForm` or attempting to extend the `UserCreationForm` or `UserChangeForm` classes.

The moment `forms.py` is loaded, the following error occurs:
```
  File "/Users/user/ttt/.venv/lib/python3.6/site-packages/improved_user/forms.py", line 7, in <module>
    from .models import User
  File "/Users/user/ttt/.venv/lib/python3.6/site-packages/improved_user/models.py", line 12, in <module>
    class User(AbstractUser):
  File "/Users/user/ttt/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 118, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class improved_user.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

For the record, the offending line of code also exists in your `factories.py`, and causes the same error when imported. If UserFactory is intended to be available for import/extending, then the fix will have to be applied to both files.

## Context
In my project, I am already importing `AbstractBaseUser` in order to add more fields. To also provide a custom `UserAdmin` class to show all my extra user model fields, I included the following in my `admin.py`:
```
from improved_user.forms import UserCreationForm, UserChangeForm
from .models import User

class UserAdmin(BaseUserAdmin):
    # The forms to add and change user instances
    add_form = UserCreationForm
    form = UserChangeForm
```

The import above causes the error.

## Steps to Reproduce the Problem
1. Create a new Django project with a new Django app.
2. Run `pip install git+https://github.com/jambonsw/django-improved-user.git`.
3. Include the sample code above.
4. Run a Django `check` to trigger the error.

### PR DESCRIPTION
**Pull request by securedirective**
So far, I've found that this will fix Issue #49. But I have not yet figured out how to write the tests.

As far as I can tell, `setup.py test` does not run the tests within `example_extension_project` and `example_integration_project`. Thus, no test I write there will show the issue.

I'd like to help write the test, though. Let me know how to proceed.

### CODE REVIEW

**Comment by jambonrose** [comment]
Thank you for the PR!

There's a bunch to cover, so I've split each topic up into a separate section below. I'm going to quickly talk about credit, codestyle, failing tests, and then answer your question about running and writing tests.

## 1. Credit
You've opened issues and a PR! You should definitely add your name to the `AUTHORS.rst` file (unless you don't want to), with any contact info you deem appropriate (or none). It's currently sorted by first name.

## 2. Current TravisCI Errors
If you take a look at the [TravisCI build for this branch](https://travis-ci.org/jambonsw/django-improved-user/builds/288079971), you'll note that there are several failures. This is due to problems with codestyle and errors with documentation.

### 2.1 CodeStyle
Code must adhere to rules set by `flake8` and `pylint`, and Python imports must be sorted with `isort`. To fix some of the errors, you can simply run `$ isort src` from the root of the project. Errors shown by running `$ flake8 src` and `$ pylint -d duplicate-code -d fixme src` must be fixed manually.

**NB**: If you see 'No config file found, using default configuration' when calling `pylint`, please specify the `.pylintrc` config file found in the root of the project with the `--rcfile=` option.

### 2.2 Documentation
```pytb
django.core.exceptions.FieldError: Unknown field(s) (full_name, short_name) specified for User
```

The documentation configures Django in `docs/conf.py`, but the configuration is still using the default User model. Given the changes in the code, this configuration must now specify `AUTH_USER_MODEL='improved_user.User'`. See `runtests.py` for code.

### 2.3 Django Development Errors
The Travis build is also showing errors for the next version of Django (2.1). I've run the tests on the development branch of `improved-user` and confirm their existence is not due to changes in this branch. We can safely ignore errors when installing Django from `https://github.com/django/django/archive/master.tar.gz` (these should be dealt with in a different branch/PR).

## 3. Running Tests
The project supplies unit tests and integration tests, and you run the two in very different ways. (The `runtests.py` script runs only the unit tests for the project.)

### 3.1 Running Integration Tests in Example Projects
 You may run the example project code just as you would any Django project.

```console
$ cd example_integration_project && python manage.py test
```

### 3.2. Tox: Run All The Tests
The bad news is that you'll need to first install Python 3.4, 3.5, and 3.6 on your system.

The good news is that once you have those installed, you can run all of the tests with a single command.

```console
$ tox
```

Tox will run both unit and integration tests (from both example projects) in multiple versions of Python and Django. It will also lint the project in Python 3.6, and build the documentation in Python 3.5 (mimicking the ReadTheDocs system).

Note that the project's tox setup allows for running specific tests. For example:

```console
$ tox -e py34-django18-extension user_extension.tests.ExtendedUserModelTests.test_user_creation
```

This allows you to avoid running the whole test suite on all versions, and enables you to avoid switching environments all the time for each Python/Django dependency.

## 4. Writing Tests
The issue is one of integration, and so we must write integration tests. The example projects are just that: Django projects. To test integration, we treat the code as if it were an external Django project, and use the feature in question: we import an abstract form from `improved_user` and then test it as we would in our project. In `improved-user`'s example project cases, writing tests for these features usually involves copying a unit test that checks for success, modifying it to suit the new behavior, and running the tests.

## 5. Next Steps
I think the quickest/easiest thing here will be for me to get the tests out of your way (but check my code for problems, and feel free to add/modify). I'm going to write these tests in a new branch, make sure they fail, and then cherry-pick them onto this branch. I'll let you deal with the rest of it. 😃

**Comment by jambonrose** [comment]
Naming is hard.

The existing `example_extension_project` didn't actually extend the User model, and wasn't actually a good place to test this integration. I renamed the project `example_replacement_project` (because it replaces the improved User model with mixins), and I generated a new `example_extension_project`, wherein I actually extended the User model, forms, and factory. Unfortunately, this makes the diff for this PR a little hairy (but you can go commit by commit to see the changes - Github lists them out of order, so the command line may be easier), but I think this change will ultimately be a good thing, as it's clearer what each example project now does.

I plan to add tests to see how subclassed forms and factories behave with replacement User models, but I think that work is currently outside the scope of this PR.

@securedirective: After taking much longer than anticipated, I opted to fix the linting issues and get the documentation working. I hope you don't mind. The only thing left is for you to look this over, make sure I haven't botched anything, and to add yourself to the `AUTHORS.rst` list.

**Comment by securedirective** [comment]
Wow, you sure did a lot of work on this! :) I'll look it over.

But wait... how in the world were you able to push to *my* branch?

**Comment by securedirective** [comment]
Ok, I've looked it over and added myself as a contributor. Splitting things into 3 separate example projects is a great idea!

But I am shocked at how much overhead had to be modified to accommodate that. Thanks for taking that one, as fully understanding your complex development setup with tox and linters would take much more time than I have.

I can at least confirm that this PR still contains my contributed 4 lines of code, the tests seem to pass (including the example projects), and the use of this package in my real-life website works great!

**Comment by jambonrose** [comment]
> But wait... how in the world were you able to push to my branch?

✨ Magic✨ 

**In actuality:** If you select the option to allow edits from reviewers, Github allows repo-owners to push to the branch associated with the PR.

With regard to overhead: to be fair I could have done less work if I'd named the new project differently, but once I notice something is named badly it *really* gets to me. So, the diff looks much worse that it actually was.

Thank you for all your work! 🎉

**Comment by securedirective** [comment]
No problem. This was fun!

**Pull request merged**
